# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d74d632c50776fb694c8c08ffaa676fab7863f5b177e610ebed2bfa3b446f76273f0e6286a724afc87c871d95c44a73b329541781d97cf9b3e85fb75b80b53d2

test:
  secret_key_base: ed6771d69d609f7bc86d6c7a2935ad5e4f583b2e6217d3159d793adcf68fc2f9d54288ffc25192690efaab5f1fde32f7854c91749a8f18dd6ed98bfa7cd66729

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
